/*
 * Out2Gui.java
 *
 * Created on 2 november 2007, 19:50
 */

package outfit;

//import com.sun.org.apache.bcel.internal.classfile.JavaClass;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 * GUI for ACR120 Card reader functions
 * TODO: make it a lot nicer and more useable
 *
 * nov'08: The GUI main panel has a background image. The creation code for the
 * main JPanel has been changed using the netbeans custum code design option.
 * A new JPanel child class had been added (ImagePanel.java).
 * 
 * @author  jand
 */
public class ReaderGui extends javax.swing.JFrame {
    /** Association to RFID Reader object */
    private ACRReader reader;
    /** Association to the IvIBot ReaderLocker device */
    private ReaderLocker locker;
    
    /** 
     * fill in the reader field that is used for the association with the
     * ACRReader class
     * @param reader - the ACRreader object to manipulate with
     */
    public void setReader(ACRReader reader){
        this.reader = reader;
    }
    /** Creates new form MainFrame */
    public ReaderGui() {
        locker = new ReaderLocker();
        reader = new ACRReader();
        initComponents();
        reader.openReader();
        statusText.setText(reader.getMessage());
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        statusText = new javax.swing.JLabel();
        serialText = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        messageLbl = new javax.swing.JLabel();
        WriteString = new javax.swing.JButton();
        ReadString = new javax.swing.JButton();
        StringText = new javax.swing.JTextField();
        stringRead = new javax.swing.JLabel();
        ReadStringEcho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YourFit");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        statusText.setText("...");

        serialText.setText("--");

        statusLabel.setText("Last status message: ");

        messageLbl.setText("Tag serial:");

        WriteString.setText("Write String");
        WriteString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteStringActionPerformed(evt);
            }
        });

        ReadString.setText("Read String");
        ReadString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadStringActionPerformed(evt);
            }
        });

        StringText.setText("String");

        stringRead.setText("Last read string:");

        ReadStringEcho.setText("...");
        ReadStringEcho.setMaximumSize(new java.awt.Dimension(12, 30));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WriteString)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(messageLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serialText, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                        .addGap(241, 241, 241))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(ReadString)
                        .addContainerGap(478, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(StringText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addContainerGap(452, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(225, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(stringRead)
                        .addContainerGap(483, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(ReadStringEcho, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(StringText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WriteString)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReadString)
                .addGap(70, 70, 70)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLbl)
                    .addComponent(serialText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stringRead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadStringEcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** keep reading tags every second
        TODO: move this timer stuf outside of the GUI 
     */
    /** close the reader and connection */
    /** Open the cardreader at selected COM port */    
private void WriteStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteStringActionPerformed
        String string = StringText.getText();
        long serial = reader.readTag();
        if(string.equals("")){
            string = "Empty";
        }
        reader.writeString(string);// TODO add your handling code here:
        statusText.setText(reader.getMessage());
        serialText.setText("Serial = " + serial + " hex:" + Integer.toHexString((int)serial).toUpperCase());
        StringText.setText("");
}//GEN-LAST:event_WriteStringActionPerformed

private void ReadStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadStringActionPerformed
        reader.readString(); // TODO add your handling code here:
        long serial = reader.readTag();
        statusText.setText(reader.getMessage());
        ReadStringEcho.setText(reader.readString());
        serialText.setText("Serial = " + serial + " hex:" + Integer.toHexString((int)serial).toUpperCase());
}//GEN-LAST:event_ReadStringActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ReaderGui().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReadString;
    private javax.swing.JLabel ReadStringEcho;
    public javax.swing.JTextField StringText;
    private javax.swing.JButton WriteString;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel messageLbl;
    private javax.swing.JLabel serialText;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusText;
    private javax.swing.JLabel stringRead;
    // End of variables declaration//GEN-END:variables
    
}
